import type { Metadata } from "next";
import AuthProvider from "./context/AuthProvider";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "True Feedback",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`antialiased`}>
          {children}
          <Toaster position="top-center" />
        </body>
      </AuthProvider>
    </html>
  );
}
